add last step image configuration
TYPO3-Documentation/TYPO3CMS-Guide-Installation pull request #215
Opened 2021-06-09 21:22 UTC by franzholz

I always forget the real last step.

2021-06-10 06:39 UTC, mbrodala requested changes

2021-06-10 06:39 UTC, mbrodala commented on Documentation/QuickInstall/TheInstallTool/Index.rst
> +#. In the last step you verify the image handling settings under the configuration presets
That's not the last step for setup however. It's a check which can be done independently from the setup.

2021-06-10 06:39 UTC, mbrodala commented on Documentation/QuickInstall/TheInstallTool/Index.rst
> +     C:\Program Files\ImageMagick-7.0.11-Q8
This part does not really make sense. What is the user supposed to then? If this should be a hint that IM/GM should be installed and this path should be set in TYPO3 then we should say so. However I assume this is already spelled out clearly by TYPO3 itself ...

2021-06-15 10:11 UTC, mbrodala commented on Documentation/QuickInstall/TheInstallTool/Index.rst
> +#. In the last step you verify the image handling settings under the configuration presets
That's true but still this is not part of the installation setup process. We should mention this separately after the official steps.

2021-06-15 10:13 UTC, mbrodala commented on Documentation/QuickInstall/TheInstallTool/Index.rst
> +     C:\Program Files\ImageMagick-7.0.11-Q8
You should at least mention (using `:guilabel:` and/or `$GLOBALS['TYPO3_CONF_VARS']` path) where this path should be entered.

2021-06-26 08:57 UTC, susannemoog requested changes

2021-06-26 08:57 UTC, susannemoog commented on Documentation/QuickInstall/TheInstallTool/Index.rst
> +After the last step of the installation you must verify the image handling settings
IMHO this is the wrong location for this documentation. The next section (after the one changed here) is still on the last page of the installer. There is no way to access the config for image settings from the installer, without simultaneously completing the installer. 
I would argue that the image settings belong to https://docs.typo3.org/m/typo3/guide-installation/10.4/en-us/In-depth/TheInstallTool/Index.html#the-install-tool-in-depth (at the bottom, image handling).

2021-06-26 09:44 UTC, linawolf commented
I agree with Susy. Please move this to  https://docs.typo3.org/m/typo3/guide-installation/10.4/en-us/In-depth/TheInstallTool/Index.html#the-install-tool-in-depth and make a new PR about that. I am closing this PR for now.

2021-06-26 09:44 UTC, closed without merging