[TASK] Add section on core upgrader
TYPO3-Documentation/TYPO3CMS-Guide-Installation pull request #382
Opened 2024-05-16 15:21 UTC by garvinhicking

References #273

I'm a bit unsure if we really want to add this due to the forking/maintenance nature, but on the other hand it could be helpful.

2024-05-16 16:47 UTC, linawolf approved these changes

2024-05-17 07:55 UTC, froemken requested changes

2024-05-17 07:55 UTC, froemken commented on Documentation/Tools/Index.rst
> +`wapplersystems/core-upgrader`, compatible up to TYPO3 v12) with).
`with)` is too much

2024-05-17 08:15 UTC, garvinhicking commented on Documentation/Tools/Index.rst
> +`wapplersystems/core-upgrader`, compatible up to TYPO3 v12) with).
```suggestion
`wapplersystems/core-upgrader`, compatible up to TYPO3 v12).
```

2024-05-17 08:15 UTC, garvinhicking commented on Documentation/Tools/Index.rst
> +`wapplersystems/core-upgrader`, compatible up to TYPO3 v12) with).
thanks!

2024-05-17 20:46 UTC, froemken approved these changes
We at jweiland.net also work with either old core-upgrader or new core-upgrader. These extensions are only a collection of all original TYPO3 Core Upgrade classes. So, for me it's not a problem to mention these community extensions.

2024-05-18 09:38 UTC, brotkrueml commented on Documentation/Tools/Index.rst
> +The extension allows to perform multiple TYPO3 core version upgrades in one step by offering
```suggestion
The extension allows to perform multiple TYPO3 Core version upgrades in one step by offering
```

2024-05-18 13:21 UTC, merged